apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tap-bcr-demo
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tap-bcr-demo
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/sample-accelerators/tap-bcr-demo
      ref:
        branch: main
